name=ESP32TelegramBot
version=1.0.0
author=Mahadi Hasan
maintainer=Mahadi Hasan
sentence=A lightweight and memory efficient Telegram Bot library for ESP32 microcontrollers
paragraph=Designed specifically for embedded systems where heap memory and stability are critical. It parses only essential message fields using ArduinoJson filter deserialization to prevent memory fragmentation.
category=Communication
url=https://github.com/mahadihasan9/ESP32TelegramBot
architectures=esp32
depends=ArduinoJson (>= 7.0.0)
